### ISSUE TITLE
When trying to compile it gets really slow and crashes

### ISSUE THREAD

**Issue by OltiP2** [ripose-jp/Memento#102]
Manjaro Linux 21.2.6
it crashes and the only thing i can move is my mouse but i cant shut it of i need to forcefuly turn it of by holding the power button i tried 2 times but i dosent work the same issue

**Comment by ripose-jp** [comment]
What is the "it" you're referring to? Manjaro or Memento?

Anyway, there's no reason to compile Memento manually on Manjaro, just run `pamac build memento` and it handles everything.

**Comment by ripose-jp** [comment]
Installing Memento from the AUR just automates the build process. There's no difference between building it manually and using the AUR version.

>you said i was more stable

It's not more stable, it links to dependencies dynamically. This is better because it means Memento will theme properly with your system on Linux and it can take advantage of features added in new versions of dependences such as mpv.

I'm closing this because there's not really anything to solve.
