### ISSUE TITLE
Unify kana term entries

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#106]
Depending on the dictionary, pure kana terms may or may not have the identical kana in their kana (reading) field. Memento currently lists kana term entries that have a reading and those that don't as two terms, and furthermore audio lookup does not work for kana terms that don't have reading. It would be nice if the entries could be unified under one term like Yomichan's behavior.

**Comment by Calvin-Xu** [comment]
> I need more information on how to reproduce this. If you can give me a dictionary and an example word where the behavior between Memento and Yomichan is different, that would be best.

Unfortunately I'm been typing on a phone and not in a position to test thoroughly.

One example I can recall is さめざめ. Two terms/groups are generated, and I think jmdict & デジタル大辞林 are in one group while ハイブリッド新辞林 is in another. Most kana terms should trigger this behavior. I think Yomichan always combines terms; I haven't noticed any duplicate entries where one has reading and one doesn't.

**Comment by ripose-jp** [comment]
I finally found a dictionary that does what you describe. Unlike every other dictionary, this one has the same thing in the `reading` and `expression` column. I can't think of any good reason why, but I might be able to account for this using SQL. I might also be able to filter for it during adding dictionaries, but this would require re-adding dictionaries or updating the DB version. I'll consider my options.

![image](https://user-images.githubusercontent.com/72582120/170839817-348dbef9-be2c-4e06-ac58-2a1788bfe082.png)

**Comment by Calvin-Xu** [comment]
I just got to my computer. Turns out さめざめ happens to not work for ハイブリッド新辞林 so I apologize for the inaccuracy.

![image](https://user-images.githubusercontent.com/28978265/170840317-03ea3adf-20b3-4f12-896a-81fc7d7aefb8.jpeg)

![image](https://user-images.githubusercontent.com/28978265/170840324-2386fb89-11e4-47bc-98b7-ed6f0d037486.jpeg)

So there should be a fair number of dictionaries that have the same thing in the `reading` and `expression`. I look forward to any option you choose.

**Comment by ripose-jp** [comment]
I've decided that I don't want to take the performance hit of filtering this stuff at search time because searches should be as fast as possible. It also adds quite a bit of complexity to the SQL queries. Doing it during add time is cheap since add time is executed once and speed there isn't critical.

I also decided to update the DB version so I can update all terms that have the same value in the `expression` and `reading` columns to use the empty string as the reading. This means that no one is going to have to re-add dictionaries. This will prevent downgrading, but I've done DB updates in the past and I don't recommend downgrading in the first place, so I think this is a fine tradeoff.

I'll merge the change into master when I'm fairly certain it is bug-free.
