### ISSUE TITLE
Adding a tutorial

### ISSUE THREAD

**Issue by Quezako** [ripose-jp/Memento#107]
Hello,

I'm trying to use Memento, but I can't see how to export to Anki.
I've set up Anki connect, target deck, etc, but I do not see any option to create card.
When I click on a subtitle, nothing happens.

I think that creating a small tutorial could be useful, either by text or video.

**Comment by ripose-jp** [comment]
I don't have any interest in creating a tutorial. Other than adding dictionaries, I think Memento is a fairly straightforward program.

I am willing to help you solve your problem if you can describe it for me.

>I've set up Anki connect, target deck, etc, but I do not see any option to create card.

If you've set up everything, the only reason you wouldn't see an option to add a card is because Memento cannot connect to Anki. This could be because Anki isn't open, you don't have the [AnkiConnect](https://ankiweb.net/shared/info/2055492159) plugin installed, or there is a bug, though the last one is not likely.

>When I click on a subtitle, nothing happens.

Nothing should happen. By default you hover your mouse over subtitles to bring up definitions. If nothing happens, no definitions were found, or you've resized your window to be comically small.

**Comment by Quezako** [comment]
Here is what I'm doing, I don't know what I am doing wrong.
https://youtu.be/9EzjcAactI4

**Comment by ripose-jp** [comment]
Thank you for the video, I can see exactly what's wrong. You're selecting the subtitle you want to search as the secondary subtitle track. You want to select it as the primary subtitle track.

![image](https://user-images.githubusercontent.com/72582120/170847473-46b545a2-9f83-4d3f-803e-619bc6b1600c.png)

Secondary subtitles are used for people that want to display subtitles in Japanese and another language. Although, until mpv v0.35 releases, it isn't possible to have both the primary and secondary subtitles on screen at the same time.

The second problem I see is that you haven't filled out your card templates yet. You can find all the markers and their descriptions by clicking the **Help** button on the Anki Integration Settings window.

![image](https://user-images.githubusercontent.com/72582120/170847563-9d6b9cce-6494-42b1-8e2e-ebf31235d897.png)

**Comment by Quezako** [comment]
Ok thank you, I think that a small documentation could be nice, especially for people who do not speak English as a mother tongue.
Yes, I did not set the Anki fields yet, since I did not understood why subtitles did not show in the first place.
Thanks for the clarification.
