### ISSUE TITLE
Degraded experience during JapanesePod101 outage

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#112]
It seems that JapanesePod101's audio service is down, at least from my end. This seems to happen once or a few times a year judging from Yomichan's discussions (e.g., https://github.com/FooSoft/yomichan/issues/676#issuecomment-660668881).

Currently, Memento is affected when JapanesePod101 is down. Even if JapanesePod101 is ranked under another audio source (Forvo), adding card to Anki results in hanging, a popup "Operation canceled", and the {audio} field being populated with `HTTPConnectionPool(host='assets.languagepod101.com', port=80): Max retries exceeded with url: /dictionary/japanese/audiomp3.php?kanji={...}&kana={...} (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x1156b1610>, 'Connection to assets.languagepod101.com timed out. (connect timeout=10.0)'))` when the card is eventually added to Anki.

I wonder if Memento can handle this situation better; perhaps Audio Source settings can have the option to disable an audio source? Or I can understand that this happens rarely enough to warrant fixes.

**Comment by ripose-jp** [comment]
This is actually all handled by AnkiConnect not Memento. Memento simply passes the URL of the audio clip to AnkiConnect through the `url` field in the [`addNote`](https://github.com/FooSoft/anki-connect#note-actions) action. You can test that Memento actually fails gracefully in this situation by playing an audio clip inside of Memento. It will simply show the audio clip not found icon and play nothing.

I'm closing this because it's not something that's in my hands.
