### ISSUE TITLE
[Feature Request] Change {glossary-brief} Term Marker to a more compact layout

### ISSUE THREAD

**Issue by Juiin** [ripose-jp/Memento#121]
Similar to my suggestion for adding a Compact Glossaries option for Defintions within the search window. I think it would be a nice QoL Feature, if the already existing {glossary-brief} Term Marker, displayed the definitions separated by a | or , on the same line instead of omitting the dictionary name. I've included a few screenshots to illustrate what i mean.

With memento and {glossary}
![memento-noncompact](https://user-images.githubusercontent.com/22873303/194556147-443ffde5-4a7f-4b90-ac3f-08bcedf8508b.png)
With memento and {glossary-brief}
![memento-brief](https://user-images.githubusercontent.com/22873303/194556188-91afe80a-93bd-4c44-ae67-b6125f8bbe3b.png)
With yomichan
![yomichan](https://user-images.githubusercontent.com/22873303/194556212-bdd1b43a-baa9-4c34-9614-e77581361940.png)

I think the last screenshot, would be an ideal solution for readability and compactness. Since some words have quite a few definitions this would eliminate the need for scrolling on most cards.

Awesome job with this tool by the way! I think it's the best one out there for watching Anime.

**Comment by ripose-jp** [comment]
I'm not going to change the behavior of `{glossary-brief}` just because there may be people who depend on the current behavior and don't expect it to change. I see no problem adding a new option called `{glossary-compact}` that does what you want. It shouldn't take long. I'll probably get it done this weekend.

>Awesome job with this tool by the way! I think it's the best one out there for watching Anime.

Thank you for the praise. I don't really say it, but it's always nice to get feedback, good or bad.

**Comment by Juiin** [comment]
That's fair. I would have considered it an upgrade to the current behaviour. But adding a new option is a safe call. I'm looking forward to the update!
