### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by adriannedbailo** [ripose-jp/Memento#149]
Can I use it for learning other languages? How can I set other dictionaries or something like that?

**Comment by Calvin-Xu** [comment]
According to https://github.com/ripose-jp/Memento/blob/master/CONTRIBUTING.md, your best chance is to start a fork. Memento is suitable only for Japanese mainly because: 1. dictionaries in Yomichan format on the Internet are all for Japanese, as Yomichan is an extension for Japanese, but you can load any compatible dictionary for other languages you find 2. Memento uses MeCab for text segmentation/tokenization, which is meant for Japanese. This means you most likely will not be able to automatically select / lookup words in different languages via mouseover in Memento.

**Comment by ripose-jp** [comment]
You can do anything you want, but Memento is built for learning Japanese. I won't be adding support for other languages because I'm not learning other languages. The reason Memento is worth using is because I know just enough about Japanese to make it work. I know nothing about French, Russian, Tagalog, or any other language you may consider trying to use Memento with. You are welcome and encouraged to fork Memento if you want to take the foundations established by it and build it out to work with another language.

**Comment by X-49** [comment]
Hi guys. How can I use Memento to learn English? My native language is Russian. I like that Memento is based on Qt6 and is available for macOS, unlike Haruna and mpc-qt, but I'm not particularly interested in learning Japanese. I will not be able to make a fork of the project for English, it is quite a difficult task for me.

**Comment by X-49** [comment]
> You can do anything you want, but Memento is built for learning Japanese. I won't be adding support for other languages because I'm not learning other languages. The reason Memento is worth using is because I know just enough about Japanese to make it work. I know nothing about French, Russian, Tagalog, or any other language you may consider trying to use Memento with. You are welcome and encouraged to fork Memento if you want to take the foundations established by it and build it out to work with another language.

Hi guys. How can I use Memento to learn English? My native language is Russian. I like that Memento is based on Qt6 and is available for macOS, unlike Haruna and mpc-qt, but I'm not particularly interested in learning Japanese. I will not be able to make a fork of the project for English, it is quite a difficult task for me.

**Comment by ripose-jp** [comment]
If you created a Russian to English dictionary in Yomichan's dictionary format, you could use it to learn English, but it would not work well. Memento cannot deconjugate English words, so it is likely that a word like "work" may show up in searches, but words like "worked", "working", or "works" will not. Something like [interSubs](https://github.com/oltodosel/interSubs) may work better for you.
