### ISSUE TITLE
[Linux] Can't install dictionaries: "Could not open database"

### ISSUE THREAD

**Issue by eshrh** [ripose-jp/Memento#15]
I can't seem to open any dictionaries, even jmdict_english.zip. I get "Could not open database."
I am on arch linux, and i built the source from 0.4.7-alpha from the makefile. 

Running the program from the command line gives nothing out of the ordinary other than `[file] Cannot open file '/home/<name>/.config/memento//input.conf': No such file or directory` which makes sense because i never made one, and also "Could not open dictionary database." I'm not sure what could be causing that.

**Comment by ripose-jp** [comment]
You can safely ignore any errors from mpv about configuration files because they aren't strictly necessary.

As for the dictionary problem, could you tell me if you have a ```dictionaries.sqlite``` file in ```~/.config/memento/dict/```?

If you do have one, does the console show any more specific errors about the database before "Could not open dictionary database."?
A dump of stderr might be useful here since mpv likes to print a lot of stuff to stdout. This can be done by executing ```memento 2> errors.txt```. Feel free to remove any identifying information before you do.

**Comment by eshrh** [comment]
Thanks for the quick response, sorry about the delay on my end.

I didn't have the directory `~/.config/memento/dict/`. I manually created the directory, and everything worked fine. Maybe some addition to the documentation or some code that automatically creates the folder on first run is in order.

I replicated the error by deleting the dict folder again, but the stdout didn't have anything out of the ordinary other than the same "Could not open dictionary database." and nothing else.

**Comment by ripose-jp** [comment]
It should have been created by [this line in main](https://github.com/ripose-jp/Memento/blob/861ad5be0d5d4efeefcae9eea79b17bdda0ea148/src/main.cpp#L111), but clearly something went wrong.
Seems like if ```~/.config/memento/``` already exists but ```~/.config/memento/dict``` doesn't, it will never get created.
I'll be sure to fix that oversight.
