### ISSUE TITLE
Inconsistent ability to add Anki notes

### ISSUE THREAD

**Issue by snfergy** [ripose-jp/Memento#160]
Sometimes when attempting to add Anki notes by hovering over subtitles the feature isn't available. I'm not sure if this is related to the first bullet in the troubleshooting, as I'm able to do it on other sub lines.

https://dl.dropboxusercontent.com/s/7pocc7bt6ty88ta/memento_HXyNRUBXaP.mp4

**Comment by ripose-jp** [comment]
90% of the time this is related to your note template.

Set your duplicate policy to "allowed in same deck". Can you add any note?

**Comment by snfergy** [comment]
Yes, that seemed to have done the trick. How can I view what's causing the issue in particular?

**Comment by ripose-jp** [comment]
>How can I view what's causing the issue in particular?

I don't know if there is a way. Anki/AnkiConnect decide what qualifies a note as a duplicate and they don't tell Memento anything beyond that.

The reason I asked you to change your duplicate policy was to check if the problem was with your note template or Memento. The fact that changing your duplicate policy allows Memento to add cards means that your notes are being detected as duplicates Anki. You can fix this by fixing your notes or your template. You can post your template and I'll let you know if I see anything immediately wrong, but beyond that you'll have to troubleshoot yourself.

**Comment by snfergy** [comment]
It's quite a lot. I'm using a [premade deck](https://ankiweb.net/shared/info/1557722832) as a template.

Front Template: https://pastebin.com/1eCis5de
Back Template: https://pastebin.com/FkXfkK4z

**Comment by ripose-jp** [comment]
I mean your Memento template, not your Anki template. I've never written an Anki template so I can't help you debug that.

**Comment by snfergy** [comment]
https://i.imgur.com/9LtSkHX.png

**Comment by ripose-jp** [comment]
From what I've seen, `SentKanji` is probably the key that Anki uses to detect duplicates. If so, it ignores markup and just looks at the text. When you add vocab from one sentence all other in the same sentence are detected as duplicates.

Maybe add spaces around `<b>{close-body}</b>` to try and trick Anki.

This is all just speculation, I don't guarantee this will work.

**Comment by snfergy** [comment]
That worked! Thanks a lot.
