### ISSUE TITLE
Underline known words "migaku-style" using anki as a database

### ISSUE THREAD

**Issue by AxillV** [ripose-jp/Memento#169]
Would highlighting words that you already "know" (they exist in the sort field in an anki card) be possible? The program recognizes if a word exists, if you open the dictionary, but I suspect that the hard part would be deciding which letter/mora to "hover over" in order to check. Maybe it could check for all different combinations and decide on the longest (in letters/mora) result, with the user having the ability to correct the selection?

I don't know how useful this would be, though being at the early stages of language learning, being able to recognize i+1 sentences at a glance would be something that could make the process easier.

**Comment by ripose-jp** [comment]
The major problem to solve 
This can be done fast and easy with MeCab, but the issue with only relying on MeCab's results is that it only tokenizes based on data in ipadic. This isn't necessarily going to line up with what is actually available in a user's dictionary. For example, jmdict contains a lot of definitions for phrases which MeCab likely won't consider a single token.

The alternative to MeCab would be writing a tokenizer that's aware of the user's dictionaries. A simple algorithm would be for each character in the subtitle, create a token for every possible substring starting from that character then highlight all the matches. This is O(n^2) just in searches done, which is expensive since each search goes out to disk **and** Anki in order to get a result. If subtitles are on the screen for all but a second or two, there's no guarantee that you even get a result back in time unless you're preloading results.
