### ISSUE TITLE
Accept mpv-style subtitle argument from command line

### ISSUE THREAD

**Issue by eshrh** [ripose-jp/Memento#17]
I usually start my video player from the command line. With mpv, i can specify the right subtitle file with `--sub-file=<sub-file>`. I know i can still add subtitle files in memento, but it takes a few clicks in the gui with every new video file.

It would be nice if memento could also accept --sub-file(https://mpv.io/manual/master/#options-sub-file) where the given subtitle file is appended to the sub list.

This is all i really want, but as a side idea, it could be interesting to use ALL given command line options and pass them along to mpv. This would allow for some pretty powerful usage ideas.

**Comment by ripose-jp** [comment]
I was hoping that this would be as simple as just parsing command line args starting with ```--``` and calling ```mpv_set_option_string```, but it seems like mpv is inconsistent when it comes to handling options. This approach works for something like ```--volume=``` but doesn't work for ```--sub-file=```.

The workaround I'm contemplating is requiring certain options to use mpv's [per-file syntax](https://mpv.io/manual/stable/#per-file-options) since that is easier than manually handling a list of options that are incompatible with ```mpv_set_option_string```. Is this something that would bother you?

**Comment by eshrh** [comment]
No, not at all! The main usage for this is scripts anyway; so as long as it's possible it's fine.

**Comment by ripose-jp** [comment]
I was able to get ```--sub-file``` working outside of per-file syntax by applying options outside of per-file syntax to each file individually. You can think if it like an implicit ```--{ --}``` around everything. This doesn't produce behavior one to one with mpv, but its pretty close.

One thing to be aware of is that command line arguments only apply to files loaded from the command line. Files loaded from the GUI afterwards will be loaded without those arguments in effect. I think this is a reasonable compromise to make since Memento supports using an mpv.conf if you want to use any mpv options persistently.

The changes are on master.
