### ISSUE TITLE
[Likely] Crash Due to Invalid Settings Data

### ISSUE THREAD

**Issue by mansuen** [ripose-jp/Memento#172]
Hi, the latest release doesn't seem to work on my computer on a Windows 10. I used the provided installer. I uninstalled it, cleared all the folders in the Program Files, reinstalled it, rebooted, etc., with no luck. When I open memento.exe nothings seems to happen. I reinstalled v1.0.0 and it worked again. 

Thanks again for maintaining such a wonderful piece of software. We greatly appreciate it!

**Comment by ripose-jp** [comment]
v1.1.0 is working on my copy of Windows 10. The most likely thing I can think of happening is there is some invalid data in the registry and it is crashing Memento because there's no input validation for settings at the moment.

If you could, please reinstall v1.1.0 and run `memento_debug.exe` which is located in Memento's install directory. Post a screenshot of the cmd window. Feel free to censor any personally identifying information, I don't need that for debugging.

After doing that, you can try opening regedit, going to `HKEY_CURRENT_USER\SOFTWARE` and deleting `memento` and seeing what happens. You will lose all your settings doing this though.

**Comment by mansuen** [comment]
Hi! Thanks for your quick reply. Here's a screenshot of what I get after running the debugger:

![image](https://github.com/ripose-jp/Memento/assets/20325411/b3f942a8-af51-47ac-babe-68fdc7d8882c)

I deleted the regedit files and it worked! Thank you!

**Comment by ripose-jp** [comment]
I'm going to leave this open so I can track settings validation as a bug. I'm working on overhauling how Memento handles settings on the backend, so it's probably going to take a bit before I can close this.
