### ISSUE TITLE
Pause at the end of secondary subtitles

### ISSUE THREAD

**Issue by mansuen** [ripose-jp/Memento#174]
The current feature of automatically pausing at the end of the subtitles I believe is very useful for beginners like me that can't yet understand most of the sentences. However, sometimes the original and translated subtitles are from different sources and they may be unsynchronized by a fraction of a second. This is enough to make the automatic stop after the subtitles (which works with the primary subtitles) not catch in time the secondary subtitles if the latter are ahead by a bit. Additionally, when creating an Anki card, it will not have the secondary subtitles of that scene. 

It isn't too annoying, I just have to hit the left arrow to go back and try to pause just in time so I can catch the two subtitles at the same time. But it would be a nice enhancement if there was an easy way to work around this. Thank you!

Edit: I saw that you were contributing to the mpv code earlier this year to be able to adjust the delay of secondary subtitles independently to the main subtitles. Has this feature been added?

**Comment by ripose-jp** [comment]
I'll be honest, I don't like this feature and my opinions on the auto pause feature have been mixed since its inception. Essentially I don't want auto pause implemented by Memento since it can be implemented well by an mpv script, several of which exist. Implementing it in Memento is just maintenance baggage. The feature never worked reliably in my limited experience with it anyway.

Secondary subtitles seem even more useless in my opinion. I'd recommend using the , . keys to step forwards and backwards frame by frame if secondary subtitles aren't visible when you need them.

>Edit: I saw that you were contributing to the mpv code earlier this year to be able to adjust the delay of secondary subtitles independently to the main subtitles. Has this feature been added?

If the pull request is still open, no. I doubt anything will happen with that unless I start bugging mpv devs in IRC. I'll get around to it eventually.

**Comment by mansuen** [comment]
I understand your concerns. Although I must say that the auto pause has worked wonderfully for me and it's very useful as a beginner having to pause after every sentence. Just that little detail of the secondary subtitles sometimes not being caught by the pause. Thanks for the suggestion regarding adjusting the frame, it does the trick.

**Comment by ripose-jp** [comment]
I'm not contesting that auto pause is a useful feature. I'm just saying it's bad idea to implement it in C++.

As for this feature request, would you say that seeking by frame makes this feature request redundant? I just want to know whether or not to close it.

**Comment by mansuen** [comment]
Yes! Seeking by frame solves this for me. Thanks for asking.
