### ISSUE TITLE
Text not displaying well in subtitles list version 1.2.0 

### ISSUE THREAD

**Issue by OltiP2** [ripose-jp/Memento#178]
i reverted back to 1.1.0 and i don't have this problem only in 1.2.0 this problem occurs
[
![aaaaasapture](https://github.com/ripose-jp/Memento/assets/97410429/571d3c27-3591-4732-add7-d456845ef05a)
](url)

**Comment by ripose-jp** [comment]
Upload the subtitle file please.

**Comment by OltiP2** [comment]
This happens with every subtitle file
Rename the extension to srt since github doesn't let me post it:
[animeseriesdubbed Slam Dunk E055.ja - Copy.txt](https://github.com/ripose-jp/Memento/files/12365175/animeseriesdubbed.Slam.Dunk.E055.ja.-.Copy.txt)

**Comment by OltiP2** [comment]
Some subtitles get show properly and some not i can upload some "proper" ones

**Comment by Calvin-Xu** [comment]
I haven’t loaded the file up in a desktop text editor but judging by the mojibake this looks like GBK encoding (Chinese)

**Comment by ripose-jp** [comment]
It's definitely UTF-8, but Windows is treating it like Windows 1252.

**Comment by Calvin-Xu** [comment]
Interesting. On iOS Safari it looks like decoding a UTF-8 file as GBK

<img width="556" alt="image" src="https://github.com/ripose-jp/Memento/assets/28978265/8b9a52cc-5e59-4a98-b967-a57899f11733">

**Comment by ripose-jp** [comment]
The more I learn about character encoding, the more I hate it. It's UTF-8 encoded without a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark). The old v1.1.0 implementation just assumed everything was UTF-8 which led to #170 when confronted with non-UTF-8. QTextStream relies on this BOM to figure out the encoding, otherwise it just assumes the default code page. This is fine on UTF-8 systems like macOS and Linux, but falls apart on Windows because it uses 1252.
