### ISSUE TITLE
Subtitle Offset

### ISSUE THREAD

**Issue by Ryu481** [ripose-jp/Memento#186]
Could you add subtitle offset in the subtitle list like it is in animebook? It would be nice for retiming subtitles.

**Comment by ripose-jp** [comment]
I haven't used animebook extensively, so I don't know what you're referring to. Please describe your feature request and how it works.

**Comment by Ryu481** [comment]
In animebook at the end of the subtitle list you can add an offset +- to time the subtitles, because they are often out of sync. So you can add the time the subtitles are out of sync and it will shift the subtitles for the amount entered. It looks like this
https://i.imgur.com/FA5UQYO.png

**Comment by Erland-Eldrid** [comment]
> I haven't used animebook extensively, so I don't know what you're referring to. Please describe your feature request and how it works.

I was gonna open a new issue, but since mine is kinda similar, I decided to comment here.

About the primary and secondary subtitles, is it possible to retime each one independently without affecting the other? For example, the secondary subs are correctly timed, and the primary subs (the Japanese one) are not. But if I retime it by pressing Z or X, it'll affect the secondary subs as well. It'd be really helpful in I could retime each one independently.

**Comment by ripose-jp** [comment]
@Ryu481 This is already a feature in mpv bound by default to the **z** and **x** keys.

@Erland-Eldrid Unfortunately not. If this PR gets merged https://github.com/mpv-player/mpv/pull/11689 then it will be. Nothing's been happening with it for months though.

**Comment by yangmillstheory** [comment]
Re: https://github.com/ripose-jp/Memento/issues/186#issuecomment-1793240866, is it possible to offset the secondary subtitle track as well?

**Comment by ripose-jp** [comment]
`secondary-sub-delay` is an option in mpv v0.38.0, but I don't believe that it's bound to a key by default. You'll have to add binds to your `input.conf` in the config folder in order to use it.
