### ISSUE TITLE
Add option to resize screenshots before adding to anki

### ISSUE THREAD

**Issue by eshrh** [ripose-jp/Memento#19]
The user should be able to resize mpv screenshots, because otherwise images might be too big on anki cards especially when watching something in fullscreen.

Locally this was pretty easy to implement, starting on line 717 in mpvadapter.cpp, I added
```c++
    QImage img(filename);
    img = img.scaled(1000,300,Qt::KeepAspectRatio)
    img.save(filename)
```

Unforunately I'm not very good at qt or c++, so I don't know what the best way to add options to the settings ui is, but I think it would be a useful feature to be able to customize the screenshot size; and maybe an option to choose to preserve aspect ratio to height or width.

**Comment by ripose-jp** [comment]
The only reason I really haven't added something like this already is because image scaling can be done in Anki either by setting the `max-width` and/or `max-height` properties for the `img` tag in card's CSS, or by adding another field for the image, wrapping the field in `<div>` or `<span>` tags and then setting the `max-width` or `max-height` properties there.

The Anki Integration settings page is already fairly cluttered as well, so I want to be careful before I add even more complexity.

I'll have to think about this one. I may end up tagging it as a wontfix.

**Comment by eshrh** [comment]
Wow, im not sure why i didn't think about that earlier. This is definitely a pretty useless issue imo; i don't think it warrants at least like 3 checkboxes, two spin boxes, two labels, etc. It's really just not very worth it. I'm fine to close this
