### ISSUE TITLE
Can't use numpad to adjust volume

### ISSUE THREAD

**Issue by kimjongbing** [ripose-jp/Memento#195]
With this config:
`LEFT seek -2 exact
RIGHT seek 2 exact
KP_DIV adjust_volume -5
KP_MULTIPLY adjust_volume 5`

I am trying to use "/" and "*" on my numpad to adjust volumes but it does not work. On mpv this is default for me, I have tried adjusting my input.conf to match this but it does not seem to work.

I am on Windows 11.

**Comment by ripose-jp** [comment]
`KP_DIV` and `KP_MULTIPLY` are not valid key names in mpv. However, Memento sends them to mpv with the invalid names of `KP/` and `KP*`. They should be handled as if they were not on the keypad at all since arthritic keys on the numpad don't contain any special `KP` prefix when being handled by mpv. I've made a commit fixing this.

**Comment by kimjongbing** [comment]
> `KP_DIV` and `KP_MULTIPLY` are not valid key names in mpv. However, Memento sends them to mpv with the invalid names of `KP/` and `KP*`. They should be handled as if they were not on the keypad at all since arthritic keys on the numpad don't contain any special `KP` prefix when being handled by mpv. I've made a commit fixing this.

ok thanks for this, also looking forward to handlebars #79  being added since jpmn mining note doesnt work otherwise
