### ISSUE TITLE
Play audio doesn't work

### ISSUE THREAD

**Issue by ahizap** [ripose-jp/Memento#204]
![image](https://github.com/ripose-jp/Memento/assets/67712951/c3ae4f8f-24c3-4a7c-bdec-94721437c03d)

There is an button to play the audio but it doesn't work

**Comment by ripose-jp** [comment]
This was already fixed with commit 0566191821b68dfefbf560660742f10eae0e56f5. JapanesePod101 recently changed their API to redirect from JapanesePod101.com to InnovativeLanguage.com, which breaks Qt's default security policy when following redirects. In the meantime you can use other audio servers like [Yomichan Forvo Server](https://ankiweb.net/shared/info/580654285) or [Local Audio Yomichan](https://github.com/themoeway/local-audio-yomichan).
