### ISSUE TITLE
Possible selection of more characters?

### ISSUE THREAD

**Issue by vrnvorona** [ripose-jp/Memento#21]
Currently there is a problem that I can't select say all string as sentence. And sometimes even Kanji+Kana won't work, for example  楽しい, I can select only Kanji, or only Kana which is pointless.

**Comment by vrnvorona** [comment]
Is it possible/useable to select freely? Maybe with modifier?

**Comment by ripose-jp** [comment]
I'm not sure what the problem is exactly.
Assuming I'm understanding correctly, when you hover over 楽しい, you don't get any matches for 楽しい, but instead only for 楽 or しい.

Memento finds words by checking everything in the subtitle starting where you hover.
If the subtitle is something like: 日本語を通用する大和民族が国民の大半を占める。and you hover over 国, Memento will execute these searches and merges the results:
国民の大半を占める。
国民の大半を占める
国民の大半を占め
国民の大半を占
国民の大半を
国民の大半
国民の大
国民の
国

Adding manual selection wouldn't catch anything that it hasn't already tried.

If you're not getting results for 楽しい, that means that the dictionaries you're using doesn't have an entry for 楽しい. As you can see in the screenshot below, English's jmdict has entry, so results show up.

![image](https://user-images.githubusercontent.com/72582120/127786026-b90e5cb1-2780-40e5-a279-dec70d3b5870.png)

**Comment by vrnvorona** [comment]
You're right, that was different word and it was partial probably, 楽しかった but without た so it couldn't find it. 楽しい works good
