### ISSUE TITLE
Setting secondary_sub_visibility to 'auto' within the mpvacious plugin does not work

### ISSUE THREAD

**Issue by wandero** [ripose-jp/Memento#215]
Setting secondary_sub_visibility to 'auto' within the mpvacious plugin does not work.

The settings 'never' and 'always' for secondary_sub_visibility within the mpvacious plugin are functional, but 'auto' (which should make subtitles visible when the mouse hovers) does not work.

Is there a way to resolve this, or can it be implemented directly in Memento?

Thank you very much.

**Comment by ripose-jp** [comment]
If you just want secondary subtitles to show when you move your mouse to the top of the player, you can find the option in **Settings** → **Options** → **Behavior** → **Subtitles** → **Show secondary subtitles when the cursor is at the top of the player**.

I think auto doesn't work since Memento doesn't pass mouse movement to mpv. It usually isn't useful and would require notifying mpv many, many times per second. Whether or not this degrades performance, I don't know but I'm weary of doing it regardless.

**Comment by wandero** [comment]
@ripose-jp Thanks for your detailed explanation! It helped me！
