### ISSUE TITLE
Partially visible video when using display scaling

### ISSUE THREAD

**Issue by Meth69** [ripose-jp/Memento#221]
Hello,
I'd like to report a bug with Memento v1.3.0 from the AUR. I'm using Arch linux on a laptop, when using display scaling in the system settings the video in Memento is cut, only 1/4 of the video is visible, only the bottom-left part of it. When removing display scaling and bringing it back to 100% the video plays fine.
When using a high-dpi display it's often useful to have display scaling enabled and this interferes with Memento video playback, hopefully it can be fixed.
Thanks.

**Comment by ripose-jp** [comment]
Unfortunately I'm not able to reproduce this. The closest I can get is on macOS where if the video is paused and is moved between displays with different DPI scaling, the video is broken in a way similar to how your describe. Unpausing it immediately fixes it though, which leads me to believe this is a different bug. On Linux I don't see any such bug with a single display set to any level of DPI scaling using Plasma 5.

What is your desktop environment and DPI scaling settings?

**Comment by Meth69** [comment]
I'm using Plasma 6.0.4 and a 105% DPI scaling (very minimal scaling, but I have tried with other values and all seem to have the same effect).

**Comment by ripose-jp** [comment]
I don't think this is a Memento bug, but is instead somewhere upstream. Forgive me, but this explanation is going to have to get into the weeds a bit.

I was able to reproduce this bug in a KDE Neon VM at 125% DPI scaling. Stepping through the relevant code in GDB, I can see that `QScreen::devicePixelRatio()` is returning a value of `2` for any DPI scaling factor above 100%. If DPI scaling is set to 125%, the value returned should be `1.25`. This is the crux of the issue.

I can't reproduce this on my own computer using Plasma 5 with X11 and Qt6. This leads me to believe this could be a bug in Qt6 on Wayland, but that's difficult to test for without setting up more VMs. The other alternative is this bug comes from Plasma 6 somehow. I don't know how `QScreen::devicePixelRatio()` is implemented, but it probably has to interact with Plasma somehow to know what scaling is set. I think this being a bug in Plasma 6 generally is more likely since it's the newer, less stable software compared to Qt6.

Unfortunately I can't fix this. It needs to be reported upstream.

**Comment by Meth69** [comment]
I see, thanks for checking it out, for now I'll just disable DPI scaling. Thanks for making this invaluable study tool :)

**Comment by kik4444** [comment]
For what's worth, I have the same problem. I'm running NixOS and Hyprland v0.42 (though the problem appeared in older versions too). While I used a scaling factor of `1` there were no issues. But after I switched to `1.2` on my 4K monitors that's when this problem manifested.

**Comment by ripose-jp** [comment]
I just tried in in Plasma 6 using X11 and Wayland and the problem only happens when running on Wayland. Probably an issue with Wayland and Qt. Not much I can do about that unfortunately.

**Comment by ripose-jp** [comment]
So I was reading a reddit post from a Wayland hater and he mentioned in passing that Wayland stores the DPI scaling factor as an integer. Which explains why everything is broken on Wayland. I think the best possible fix is probably to add a DPI scale override option to the settings where you manually specify what your DPI scaling factor actually is so the video can properly correct its size.
