### ISSUE TITLE
usage: how to jump between subtitle sentences ?

### ISSUE THREAD

**Issue by teto** [ripose-jp/Memento#235]
Is there a way/mapping to go to next / previous subtitle in the "subtitle list" and have the video jump at that point ?
![image](https://github.com/user-attachments/assets/42121cb3-592c-47f3-b1b3-a18493893a18)

I have another question about usage: is it possible to copy/paste from the first subtitlke track ? I can hover it and a popup will show me the translation but I would like to copy parts of the subtitle (I am on wayland). The only way I could find is to show the "subtitle list" and Ctrl-C / Ctrl-V the whole sentence. By the way, this could be made more discoverable with a context menu. 
So far pretty cool. Next I will try the OCR :)

**Comment by ripose-jp** [comment]
>Is there a way/mapping to go to next / previous subtitle in the "subtitle list" and have the video jump at that point ?

You can double click any subtitle in the list to seek to it. The double arrow buttons also seek to the next and previous subtitles. You can also use **Ctrl+Left** and **Ctrl+Right** to seek to the previous and next subtitle respectively. This last one is an mpv bind. Default binds are documented [here](https://mpv.io/manual/stable/) and [here](https://github.com/mpv-player/mpv/blob/master/etc/input.conf).

>is it possible to copy/paste from the first subtitle track?

The subtitles are read only and non-selectable. You can copy it to clipboard by double clicking it. Since this is bound to toggling fullscreen by default, I'd recommend disabling that mpv bind if you want to use that feature. There is no way in Memento to only select a portion of the subtitle. The act of moving the cursor over the subtitle triggers searches and searches end up selecting text, so implementing something like that isn't really in the cards.

>By the way, this could be made more discoverable with a context menu.

The last bit of hidden functionality is that **Shift+Ctrl+c** copies the audio of the current selection in the list. Maybe it's worth adding a context menu to document those secrets.

**Comment by teto** [comment]
thanks for the answer :)
