### ISSUE TITLE
Can't build with CMake versions older than 3.13

### ISSUE THREAD

**Issue by dxing97** [ripose-jp/Memento#24]
`install(TARGETS)` only supports installing targets created in the same directory on CMake releases older than 3.13. Memento's minimum required cmake version is 3.1.

see: https://stackoverflow.com/questions/34443128/cmake-install-targets-in-subdirectories

Ubuntu 18.04 LTS still ships with CMake 3.10.

**Comment by ripose-jp** [comment]
My bad, I was a little fast and loose with version requirements since I run a bleeding edge distro.

That said, I've kind of given up on focusing a ton of energy on Debian-based distros since the packages are ridiculously out of date. For example, Ubuntu 20.10 is still running Qt 5.14 even though Qt 5.15 has been out for well over a year. This is a nuisance for me because Memento depends on features added in Qt 5.15.

[The mpv devs also have similar problems with Debian/Ubuntu refusing to update mpv even though the version they're currently distributing has as known CVE.](https://twitter.com/mpv_player/status/1386341169341337602)

I may look into flatpaks or appimages to fix this problem for people running Debian-based distros, but the majority of bug reports I get form Linux users are from people running Arch-based distros, so I'm uncertain how much demand there is for that sort of thing.

**Comment by ripose-jp** [comment]
I somehow was able to get Memento to build on Ubuntu 18.04 by chasing down up to date versions of all the packages I needed. I made an [AppImage](https://github.com/ripose-jp/Memento/releases/download/v0.5.0-1-beta/Memento_Linux_x86_64.AppImage) that should work for systems with GCC 7 or later if you're still interested. Though I can't vouch for how stable it is and still recommend building from source if you can.
