### ISSUE TITLE
Error adding dictionaries

### ISSUE THREAD

**Issue by makkusumak** [ripose-jp/Memento#31]
Tried several dictionaries zip files I already used for Anki 
But still receiving same error 

Error adding dictionaries
Could not open database

Thanks

**Comment by ripose-jp** [comment]
Can you tell me your operating system and Memento version?
If you are on 0.5.1, does the file `dictionaries.sqlite` show up in the configuration folder? You can check this by going to Settings > Open Config Folder.

**Comment by makkusumak** [comment]
Hi thanks for the quick reply.

Windows 7 Home Premium is the OS.
Memento version  0.5.1-beta
confirming the "dictionaries.sqlite" file is the config folder

**Comment by ripose-jp** [comment]
I just tested v0.5.1-beta on Windows 7 Ultimate and was not able to reproduce the bug after deleting all registry entries and config folders so it would behave as if it were a new install.
![screenshot](https://user-images.githubusercontent.com/72582120/133938230-c1efae3f-8329-45d3-92cd-4b032313fbf2.PNG)

First I would like you to try deleting `dictionaries.sqlite`, starting Memento, and then trying to add a dictionary.

If that doesn't work, please download this version of Memento, https://litter.catbox.moe/ucewtj.zip, and place memento_debug.exe in your install directory, and run it. The only difference between this and the release version, is this version opens a console window on Windows that outputs debug information.

Please include a screenshot or transcript of the error messages it outputs when you try to add a dictionary. Feel free to not include any error messages that say something like
```
[file] Cannot open file '/home/ripose/.config/memento/input.conf': No such file or directory
Failed to open /home/ripose/.config/memento/input.conf.
[input] Can't open input config file /home/ripose/.config/memento/input.conf.
```
I don't need them.

**Comment by makkusumak** [comment]
By deleting the dictionaries.sqlite and restarting Memento I am now able to load dictionaries!

Thanks!!

BTW, Is there a config you can suggest?
The subtitles however are not selectable (like in the sample picture of the Mememto website) and so do not open the required definition.

I can only double click on the sentence and this will be passed to Yomichan.
Is there any guide or config to follow?

Thanks

**Comment by ripose-jp** [comment]
There's no special config or guide to follow. You should just be able to hover over subtitles once you have dictionaries added.
![output](https://user-images.githubusercontent.com/72582120/133939251-0aea5773-cdd1-417e-8a24-6b797fe06ddf.gif)

You can of course change this to use the Shift key or some other key in the settings like Yomichan.

I recommend if you have any questions about an option in the settings to hover over it first, because it likely has a tool tip explaining it. The other thing you can do it look for the "Help" button in the options to see if there's something you need to be aware of. This will be really useful for setting up Anki integration since Memento has it's own special {markers} that aren't necessarily 1-to-1 with Yomichan.
