### ISSUE TITLE
25-30% CPU usage when idle with subs on the screen

### ISSUE THREAD

**Issue by FLESHNIK** [ripose-jp/Memento#34]
When video is stopped and no subtitles on the screen CPU usage is 0-0.2%, and when subtitles are on the screen CPU usage jumps to constant 25-30%. Other UI elements(menu bar and video controls) don't affect CPU usage much(1.5-2% maximum and only for a moment). I don't know what happens, maybe subtitles are being redrawn constantly(but why if nothing changes?).

100% reproducibility.
OS: Windows 10
Memento version: 0.5.1

**Comment by ripose-jp** [comment]
I'm aware of the issue. Problem is the subtitles need to be double rendered in order to create the stroke effect, QTextEdits are performance heavy, and QtWidgets isn't GPU accelerated.

I'm debating whether or not to move the more graphically intensive parts (the OpenGL mpv renderer and subtitles) to QML since QtQuick is GPU accelerated.

**Comment by ripose-jp** [comment]
After some investigation, it seems paintEvent is recursively calling itself. I'll see if I can find a fix.

**Comment by ripose-jp** [comment]
Fixed with commit c16b3572388da7a8987bbc09860a3377509f48c4.
A new version, [v0.5.1-1-beta](https://github.com/ripose-jp/Memento/releases/tag/v0.5.1-1-beta) has been released.
