### ISSUE TITLE
Looking up words on this subtitle causes segmentation fault

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#35]
Attempting to look up any part of the following subtitle immediately causes a segmentation fault on macOS 0.5.1-2.

```
1
00:00:00,000 --> 00:00:05,000
〝民間南極観測隊
３年ぶりに派遣決まる〞
```

The payload is attached here (.srt file before changing extension): [test.txt](https://github.com/ripose-jp/Memento/files/7234724/test.txt). The timing has been changed from the original.
 
This happens with my custom dictionaries loaded, no dictionaries loaded, and just `jmdict_english` loaded.

**Comment by Calvin-Xu** [comment]
I thought I found another string that could trigger this:

```
〝新型砕氷艦の
就航にともない―〞
```

but testing it one last time before submitting it, I suddenly could not reproduce the crash with either string. If this bug could not be reproduced at all on your end, I think I should close this issue.

**Comment by Calvin-Xu** [comment]
I now understand why I could not reproduce the issue last time. During the interval, I had changed the system dictionary of my MeCab installation from UniDic back to IPAdic in my `mecabrc`. The crash only happens when UniDic is used.

Since Memento comes bundled with / uses IPAdic by default ("with a system dictionary like ipadic on Linux and OS X"), I think this might not be a high priority issue right now.

On another note, I had thought about proposing switching to UniDic, since it is the actively maintained dictionary. But it does come at the cost of larger bundle sizes, one data file that exceeds GitHub's 100MB limit (v2.1.2), and that no mecab-unidic is currently available on AUR. I suppose if only tokenization is concerned, IPAdic might be sufficient?

**Comment by ripose-jp** [comment]
Not that it's ideal, but I'm only aware of Memento working with ipadic and NAIST-jdic. I believe way way back I tested out UniDic when choosing a dictionary to bundle with the Windows version and decided against UniDic because it was way too big to upload to GitHub without LFS and it caused crashes because it doesn't follow the exact same format as ipadic.

From my understanding, passing a -O argument to MeCab when initializing it might be able to fix it, but I couldn't find any documentation on this option, so I just didn't bother.

MeCab dictionaries shouldn't be user changable in 99% of cases, so this is a bit of a low priority bug.

**Comment by Calvin-Xu** [comment]
Thanks. I suppose it might be a good idea to close this issue for now. But perhaps we should note somewhere that Memento might crash with dictionaries other than ipadic and NAIST-jdic (possibly in the build section?) since currently the documentation doesn’t really advise against it.

**Comment by ripose-jp** [comment]
I've clarified the language in the README under the Dependencies section.
