### ISSUE TITLE
Transparent subtitle bug introduced in 4bb801f

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#44]
In versions since 4bb801f6576c1abb96be940591f529f2996ad5d3, the search (subtitle) widget is transparent (but still searchable on hover). I tested the three previous versions which all display correctly. I don't understand why it is caused in that commit though.

**Comment by ripose-jp** [comment]
Can you give me some steps on how to reproduce this?
I've used a version with that commit for a few weeks now and haven't run into any issues on Linux. I'm also not seeing any problems with the macOS version either.

**Comment by Calvin-Xu** [comment]
I finally found a reliable and portable way of reproducing this. Start Memento in windowed (not fullscreen) mode. Play [this video](https://www.youtube.com/watch?v=KTZ-y85Erus) from YouTube and select the Japanese subtitle. The subtitle widget appears fine. Fullscreen Memento, and the subtitle widget becomes transparent (but still searchable on hover as described). Exiting to fullscreen and the widget continues to be transparent. A build on cb93730f83cccc3c7e90a57148ebefcee6f8b8de does not have this bug.

Tested on macOS 12.0.1.

**Comment by ripose-jp** [comment]
I don't have time to reproduce it right now, but if I had to guess it's going to be specific to macOS because updates are disabled when switching between fullscreen and windowed mode on macOS because Memento will hang otherwise. Since that code restores the old value of updatesEnabled, it is probably restoring a disabled value due to a race condition.
Rather than reverting the commit in question, I'll probably just ifdef the code out on macOS since it isn't strictly necessary. But this is just a guess pending further investigation. If it happens on other OSes, I'll revert it.

Thanks for the report.

**Comment by Calvin-Xu** [comment]
Thank you. I've read https://github.com/ripose-jp/Memento/issues/7 before and understand that there have been issues with entering and exiting fullscreen on macOS. I am not able to test on other platforms at the moment but I think this is probably a good way of addressing this.
