### ISSUE TITLE
Video not showing, just a blank screen.

### ISSUE THREAD

**Issue by ElaxDev** [ripose-jp/Memento#48]
I initially used the program in another computer since the one I normally use was broken, I had it fixed some days ago and I installed the program in it and installed dictionaries but when I went to play the video it didn't show anything just a blank screen, the audio plays, the subs show but the video doesn't show up:

![image](https://user-images.githubusercontent.com/31047609/147217160-d617b7eb-1a9f-41de-9461-004c8cce2a12.png)

And it happens with every video. When I play the video in mpv it doesn't happen though:

![image](https://user-images.githubusercontent.com/31047609/147217041-c4169109-0dcd-420f-965a-df585d42b1d2.png)

I tried reinstalling the program but the same happens.

**Comment by ripose-jp** [comment]
Pretty certain it's a problem with your GPU's OpenGL implementation.

Can you add `msg-level=all=v` to Memento's `mpv.conf`? You can get to the config folder by going to Settings > Open Config Folder. Then go to Memento's install directory, open the executable called `memento_debug.exe`, and load a video.

Post the output on the console window. Screenshots are fine. You can omit errors about missing config files and lines containing file paths.

**Comment by ripose-jp** [comment]
I found some undefined behavior related to the initialization of mpv's OpenGL renderer that was added in v0.5.2-beta.
I doubt this is what's causing your problem since the most likely outcome is a crash, but it's worth upgrading to v0.5.2-2-beta first to see if it fixes the issue.

**Comment by ElaxDev** [comment]
> Pretty certain it's a problem with your GPU's OpenGL implementation.
> 
> Can you add `msg-level=all=v` to Memento's `mpv.conf`? You can get to the config folder by going to Settings > Open Config Folder. Then go to Memento's install directory, open the executable called `memento_debug.exe`, and load a video.
> 
> Post the output on the console window. Screenshots are fine. You can omit errors about missing config files and lines containing file paths.

![image](https://user-images.githubusercontent.com/31047609/147372385-1aa9df36-5663-4150-ad19-a6fc51110829.png)

![image](https://user-images.githubusercontent.com/31047609/147372396-5374e9f8-90a1-4d0e-b7a1-72d9e0a7c7a3.png)

![image](https://user-images.githubusercontent.com/31047609/147372409-b671445e-fb6e-4d94-bf26-a6afc39f8cc0.png)

**Comment by ElaxDev** [comment]
> I found some undefined behavior related to the initialization of mpv's OpenGL renderer that was added in v0.5.2-beta. I doubt this is what's causing your problem since the most likely outcome is a crash, but it's worth upgrading to v0.5.2-2-beta first to see if it fixes the issue.

Ok, I just updated but the problem still persist.

**Comment by ripose-jp** [comment]
I was hoping that an error message would be thrown, but nothing jumps out. Can you try adding `hwdec=no` to your `mpv.conf`?

**Comment by ElaxDev** [comment]
The same happens, I don't understand very well how this works but is Memento using a different version than the latest mpv internally?

**Comment by ripose-jp** [comment]
The latest version is using mpv v0.34.0 and the versions before that were using mpv v0.33.0. From my understanding, when mpv is embedded in another program it uses `vo=libmpv`. The docs suggest that `vo=libmpv` is roughly equivalent to `vo=gpu`. I don't know what `vo` your mpv is using, but that's something you can check if you can figure out a way to read stdout on Windows.

I don't think this a bug I can fix. I haven't been able to reproduce it on any system, so it seems like it's closely tied to your hardware. If I had to guess, the bug is somewhere between mpv's OpenGL renderer and your GPU's OpenGL implementation. That's something the mpv project would have to fix on their end.

I recommend using an alternative to Memento like Animebook, asbplayer, or something else. If you want to keep using Memento, you could try installing Linux and hope everything works. If you choose to go that route, Manjaro would probably be the best option since it has access to the AUR where I maintain a package for [Memento](https://aur.archlinux.org/packages/memento/). Sorry I couldn't help.

**Comment by ElaxDev** [comment]
I updated my graphic drivers and it fixed! So I guess you were right and it was a problem with my hardware or something like that, since it has been fixed and it wasn't a Memento problem I'll close this.
