### ISSUE TITLE
Shift select behavior bug

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#49]
Selecting continuous blocks of subtitles from the subtitle list with shift click has unexpected behavior in some scenarios.

![2021-12-27 18 58 25](https://user-images.githubusercontent.com/28978265/147524333-798cf37c-8a10-4ea4-9062-16dc2ad455fe.gif)

Subtitles in question:
```
892
00:59:21,015 --> 00:59:24,477 
あとは どうやって忘れるかだけだ

893
00:59:24,561 --> 00:59:24,727 
（せきばらい）

894
00:59:24,727 --> 00:59:26,104 
（せきばらい）

895
00:59:24,727 --> 00:59:26,104 
役に立たなかったでは
終えられんしな

896
00:59:26,104 --> 00:59:27,146 
役に立たなかったでは
終えられんしな

897
00:59:27,272 --> 00:59:31,818 
し… しかし 今回の計画は
各国の注目を集めており―

898
00:59:31,943 --> 00:59:35,154 
共和国側も
我々の情報を欲しています

899
00:59:35,280 --> 00:59:38,825 
それを 敵の属国リマダとの
国境で打ち上げる…

900
00:59:38,950 --> 00:59:42,370 
だから そうするんだ
打ち上げなぞは どうでもいい

901
00:59:42,495 --> 00:59:45,540 
目当ては 共和国のリマダ駐屯軍だ
```

Other instances I have observed also have consecutive subtitle entries that start and end at the same time while having the same text content. Perhaps this is causing problems with the hash map from subtitle text to timing information?

**Comment by ripose-jp** [comment]
I've look into it and it seems like this is just how `QAbstractItemView::ExtendedSelection` works. Basically the last item you click becomes the current item, and when you shift-click another item, all the items from the current item to the item you clicked have their selections flipped.

You can work around this in several ways:
1. Click the first item you wish to select, then shift-click the second item you wish to select. This will always produce the behavior you expect.
2. Click and drag from the starting item to the ending item.
3. Ctrl-click the items you wish to select.

I'm temped to put a wontfix on this just because it doesn't seem like a trivial fix from what I've read so far.

The other option is to use `QAbstractItemView::MultiSelection` which disables shift-clicking entirely. I find it more annoying to use, though, so I probably not going to do that.

You can read more here:
https://doc.qt.io/qt-5/qabstractitemview.html#SelectionMode-enum

**Comment by Calvin-Xu** [comment]
Hmm...but at the beginning of the gif, when the highlight is on 897 (し… しかし 今回の計画は\n各国の注目を集めており―), why does shift clicking on 898 (共和国側も\n我々の情報を欲しています) select all the way down to 900?

**Comment by ripose-jp** [comment]
>If the user presses the Shift key while clicking on an item, all items between the current item and the clicked item are selected or unselected, depending on the state of the clicked item.

It's important to note that the current item and selected items aren't necessarily the same.

For some reason though it seems like the current item that is reported programmatically is not the item deciding where shift-clicking starts from contrary to what the documentation says. Rather the last item that was clicked is the item where shift-clicking is anchored to. Seems like a bug in Qt, which if it is, I can't fix it.

**Comment by ripose-jp** [comment]
I tried something else. Seems to work well. It's up on master.

**Comment by ripose-jp** [comment]
I've tested the last fix I put out quite a bit and the issue seems fixed. If there continues to be any problems, feel free to reopen the issue.

**Comment by Calvin-Xu** [comment]
Thank you! Works really great.
