### ISSUE TITLE
allow creating cards through automated subs

### ISSUE THREAD

**Issue by Astarka06** [ripose-jp/Memento#55]
It's not always 100% correct, but Japanese videos usually has harded subs and those subs usually come at the right timing. All you gotta do is finish the card yourself by editing the card with a screenshot of the hard sub or something.

**Comment by ripose-jp** [comment]
I don't understand what you're asking for.

If you want to use to create cards from hard subs, you can but you'll have to manually search for everything using the search feature with Ctrl+R. Things like `{context}`, `{sentence}`, `{audio-media}`, and `{audio-context}` won't work though since they rely on soft subs to function.

**Comment by ripose-jp** [comment]
I'm closing this because it's been a week without a response clarifying what the problem/feature request is.
