### ISSUE TITLE
Enable the SubtitleWidget to use the secondary subtitle

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#66]
Described in https://github.com/ripose-jp/Memento/issues/65

**Comment by ripose-jp** [comment]
I've considered, but I have other plans https://github.com/mpv-player/mpv/pull/9441

Although it's been sitting there for awhile so I probably need to bug some people in IRC.

**Comment by Calvin-Xu** [comment]
I agree this is a much better solution.

**Comment by ripose-jp** [comment]
mpv has merged the PR, so this issue is redundant.

3306fc095f0460df458dbd621e772edf8a8c064e adds support for constantly visible secondary subtitles if compiled against an mpv version with API 2.0 or higher. If you're running an mpv version with API 2.0 but the old version of `sub-visibility`, things will break. That should only be an issue for people running development versions of mpv though, so I don't believe it's a problem that needs to be worked around.

**Comment by ripose-jp** [comment]
The change was reverted, so back to square one.

**Comment by ripose-jp** [comment]
https://github.com/mpv-player/mpv/pull/9727 was merged, so this feature is now in Memento without having to change any code at all.
