### ISSUE TITLE
SRT Parser cannot parse empty lines

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#68]
On loading a srt file with an empty line like this:

```
4
0:00:53,860 --> 0:00:54,660


```

SRT Parser would not parse the file

```
SRT Parser: Invalid position
"\n"
```

I'm not sure if this is allowed in the spec, but seems to be pretty common and I'm quite sure Memento used to accept it.

**Comment by ripose-jp** [comment]
I don't believe there is any spec for SRT subtitles since I couldn't find anything. Most things seem to be defined by convention, and convention is SRT has 3 parts: position, timing, and text. Each subtitle is ended by **one** blank new line. It seems like the issue isn't blank subtitles, but rather using multiple blank lines between subtitles. I don't think it's worth fixing because it seems more like the input validation is working as intended.

>I'm quite sure Memento used to accept it.

The code for parsing SRTs hasn't changed in any significant way since it was added.

**Comment by Calvin-Xu** [comment]
You are right. I was remembering before SRT parsing was added and Memento was reading from mpv; and yeah, this happens when there is a blank line after a blank line:

```
26
0:02:19,390 --> 0:02:26,990
君がそうだったように

27
0:02:26,990 --> 0:03:03,370


28
0:03:03,370 --> 0:03:08,110
僕がここに忘れたもの
```

I'm encountering this issue when using Memento as a music player and loading a SRT converted from LRC lyrics. LRC does not encode end times, and each line lasts until the next line appears. Sometimes when there is a longer gap between verses, whoever makes the LRC may choose to have a blank line with only the start timestamp to end a line early.

I've changed my script to deal with this. Please close this issue if you see fit.
