### ISSUE TITLE
Newline in srt causes subtitle list to disappear

### ISSUE THREAD

**Issue by Arboco** [ripose-jp/Memento#69]
Having any newline between appearing text like this:
```
9
00:02:03,130 --> 00:02:06,100
帝国軍

中央の第４艦隊を撃破
```
Causes everything to disappear in the subtitle list like this:
![image](https://user-images.githubusercontent.com/68604956/150202110-9ac05b0f-4845-45db-a591-8c7313fa8f93.png)

Removing any such line breaks fixes the error. I have only seen subtitles for old anime have this formatting error. If this is behavior due to faulty srt files then consider this a non issue.

**Comment by ripose-jp** [comment]
It is a bug that no subtitles would appear in the list in the case that subtitle parsing failed, but it was already fixed with 93f7d9a5403ce9fa92fd7d5c80edd085664c26f2 a few days ago. The fix will make it into the next version.

Having blank lines inside of subtitle text isn't allowed in SRT subtitles, but mpv/ffmpeg is fairly permissive in what it will accept. I won't implement it into Memento's subtitle parser just because it will make implementing SRT parsing harder than it needs to be since it requires look-ahead.

**Comment by ripose-jp** [comment]
I've released v0.5.4-1 which specifically addresses this issue.
