### ISSUE TITLE
Support displaying inline images in glossary

### ISSUE THREAD

**Issue by Calvin-Xu** [ripose-jp/Memento#72]
Could be a very useful feature because diagrams are helpful and because rare kanji & math are sometimes encoded as images.

Yomichan:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/28978265/151068872-c951d070-2925-4e09-b49e-a20b8f0bca81.png">
<img width="431" alt="image" src="https://user-images.githubusercontent.com/28978265/151068362-de7bef4c-afc4-4de1-9e9a-1e7614ed7543.png">
Memento:
<img width="159" alt="image" src="https://user-images.githubusercontent.com/28978265/151069027-86c84617-11f7-4240-830c-5f41a89e4774.png">
(nothing is displayed, regardless of whether bullet points are used; possibly can be fixed in the process of supporting images?)
<img width="329" alt="image" src="https://user-images.githubusercontent.com/28978265/151068453-59d1b6f7-eb67-4ae5-a373-61abb2414b8b.png">

Related Yomichan issue: https://github.com/FooSoft/yomichan/issues/1652

**Comment by ripose-jp** [comment]
I wasn't aware dictionaries could do this.

Can you link me to a dictionary that does this and give me a word to search?

**Comment by Calvin-Xu** [comment]
"デジタル大辞泉", the dictionary provided by https://dictionary.goo.ne.jp, is shown in the examples above. I'll not link to a specific page in case that infringes copyright, but just searching for "デジタル大辞泉 Yomichan" should yield results. The terms 平方根 and 裾 shown both have images.

**Comment by ripose-jp** [comment]
I found a copy. I'll work on it when I get the time.

**Comment by ripose-jp** [comment]
I've been working on this for the past few days and so far I've gotten everything working on the front end as far as I can tell. It turns out that Yomichan dictionaries are a lot more powerful that I had originally thought. Some dictionaries use a tree-like JSON encoding called `StructuredContent` that can make tables, insert images, style text, etc. I was able to get most of it working since Qt does support most of the HTML that `StructuredContent` uses, but there are some tradeoffs.

* Images are not able to be resized dynamically. This isn't a big deal for normal searches, but will be noticeable for manual searches.
* Sizes cannot be defined by `em`s because Qt doesn't support it.
* `<ruby>` of course doesn't work because Qt doesn't support it.
 
All that's left is to make these types of entries exportable to Anki.

# Image Example

![image](https://user-images.githubusercontent.com/72582120/154826818-5c8265e5-1dc6-4687-aac7-7ec2afe9dcd5.png)

# Table Example

![image](https://user-images.githubusercontent.com/72582120/154826835-6d87cc4a-06b0-46c6-97f1-1479c5ae19bc.png)

**Comment by Calvin-Xu** [comment]
Thank you. This looks really amazing!

> Sizes cannot be defined by ems because Qt doesn't support it

I don’t know Qt so this is quite surprising. Perhaps it can be tied to the font size of the definition QLabels?

**Comment by ripose-jp** [comment]
Calculating `em`s given the font size is trivial. The problem is the fonts are set by style sheets in ancestral widgets. I don't know why, but the `font()` method always returns the wrong font, so there is no way to know what the font size is without getting hacky. Supposedly `ensurePolished()` is supposed to work, but of course it doesn't.

**Comment by Calvin-Xu** [comment]
Wow. Because the font size can be set as one of the custom stylesheets I definitely didn’t imagine so much trouble. I think just using the default definition font size (18px?) shouldn’t be too bad if all else fails.

**Comment by ripose-jp** [comment]
Doing no scaling at all is the best option. The only thing that can use `em`s are inline images.

**Comment by Calvin-Xu** [comment]
It seems it’s used by the images that are used to represent rare kanji and math, etc. (and they just use 1em)? As long as they are lined up with line height I think it’s fine.

By the way, I am wondering how `<ruby>` is handled given Qt does not support it. Can it be converted to parentheses or even superscript, or is it just omitted entirely?

**Comment by ripose-jp** [comment]
If `<ruby>` tags are properly formatted with `<rp>` tags, they should appear with parenthesis.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby

**Comment by Calvin-Xu** [comment]
That does seem to be the case. I was thinking of the behavior originally shown in https://github.com/ripose-jp/Memento/issues/73, where the ruby text is just displayed after the kanji with no indication. I don't know the standard enough to tell if the parentheses are mandatory.

I originally suspected that it might be using subscripts which I heard some of the efforts that generate Yomichan dictionaries do, but Memento already supports that. After some more digging it seems that they are doing some custom styling with `StructuredContent` to make furigana text just small and bottom-aligned:

```
["秋津", "あきず", "", "", 0, [{
	"type": "structured-content",
	"content": ["あきず 【秋津・蜻蛉】 ", {
		"tag": "span",
		"style": {
			"fontSize": "x-small",
			"verticalAlign": "bottom"
		},
		"content": "アキヅ"
	}, {
		"tag": "div",
		"content": [{
			"tag": "div",
			"content": ["（平安以後アキツとも）トンボの古名。《季: 秋》。古事記(下)「手腓", {
				"tag": "span",
				"style": {
					"fontSize": "x-small",
					"verticalAlign": "bottom"
				},
				"content": "たこむら"
			}, "に虻", {
				"tag": "span",
				"style": {
					"fontSize": "x-small",
					"verticalAlign": "bottom"
				},
				"content": "あむ"
			}, "搔き着き、その虻を―早咋", {
				"tag": "span",
				"style": {
					"fontSize": "x-small",
					"verticalAlign": "bottom"
				},
				"content": "はやぐ"
			}, "ひ」"]
		}]
	}]
}], 1910, ""]
```

Just wondering if the planned `StructuredContent` support could handle such styling.

Also, https://github.com/FooSoft/yomichan/issues/1745#issuecomment-863291766 lists a few terms from デジタル大辞泉 that use special tags should that be helpful.

**Comment by ripose-jp** [comment]
Structured content support was added on master with support for structured content in the `{glossary}` and `{glossary-brief}` markers as well.

**Comment by Calvin-Xu** [comment]
Thank you, this is wonderful. So would dictionaries need to be reimported for structured content to work? That seems to be the case.

I want to report that custom stylesheet support for `Definition` seems to no longer work. I am unable to set the font family or font size for the definition text.

**Comment by ripose-jp** [comment]
> Thank you, this is wonderful. So would dictionaries need to be reimported for structured content to work? That seems to be the case.

Only if there are image files that needed to be imported.

> I want to report that custom stylesheet support for Definition seems to no longer work. I am unable to set the font family or font size for the definition text.

When you update Memento, you should always reset your stylesheets because things change on the backend. Glossaries were changed to use a QTextEdit instead of a QLabel for reasons related to #80.

**Comment by Calvin-Xu** [comment]
Got it. Thank you.
