### ISSUE TITLE
Subtitles working incorrectly (Mac OS)

### ISSUE THREAD

**Issue by TylerChou** [ripose-jp/Memento#84]
On my Mac, the subtitles that are displayed cannot be moved and has a fixed size, and when I press v to toggle subtitle visibility, another set of the same subtitle comes up behind it, this set of subtitle can be manipulated but disappears after the next subtitle line appears.

<img width="387" alt="Screen Shot 2022-02-19 at 2 53 41 PM" src="https://user-images.githubusercontent.com/41413487/154821828-467c7d44-9dfc-4648-92f6-5ba355dbac2a.png">
<img width="383" alt="Screen Shot 2022-02-19 at 2 54 17 PM" src="https://user-images.githubusercontent.com/41413487/154821848-75b22b13-633f-4971-af83-540c93ad696c.png">

**Comment by Calvin-Xu** [comment]
The other set of subtitles are painted by mpv. You can control its visibility with `v` and manipulate it with standard mpv controls. 

Memento paints its own subtitles that you can mouse over and look up terms. You can customize the appearance of Memento's subtitles in Interface - Subtitle Search.

**Comment by ripose-jp** [comment]
Memento renders subtitles itself because it makes it possible to add hover searching. There are cases where people might prefer to use mpv's rendered subtitles instead because they like the styling or whatever else and there are options in settings to enable that. If you want to style the Memento rendered subtitles, you can follow @Calvin-Xu instructions. This is not a bug though.
