### ISSUE TITLE
Ability to use secondary sub as Anki export

### ISSUE THREAD

**Issue by TingTingin** [ripose-jp/Memento#9]
The ability to export the secondary sub file from the player as an anki export option would be nice

**Comment by ripose-jp** [comment]
This is something I've wanted to have for awhile, but it's a really difficult issue to tackle.

The way Memento handles grabbing subtitle text is it observes the [sub-text](https://mpv.io/manual/master/#command-interface-sub-text) property from mpv. The problem is that mpv doesn't provide any property to grab text from the second subtitle.

The easiest solution would be to make a pull request that adds a property like sub-text-secondary to mpv and then when that finally makes it downstream to a release, add the feature to Memento.

The other option is to go outside of mpv which is a whole can of worms I'd like to avoid after my experience trying to implement the subtitle transcript feature. In short, the reason it populates as subtitles show up rather than all at once is due to limitations with what information mpv gives about subtitles.

**Comment by TingTingin** [comment]
Thanks for the response

I don't know if this is helpful but I found this

https://github.com/SenneH/mpv2anki/blob/master/mpv2anki.lua

its a mpv script with the ability to export the secondary subs to Anki I tried going through it to see how it was done but I dont know enough about scripts to know what to look for maybe it could be helpful?

**Comment by ripose-jp** [comment]
I looked through the code and tested the plugin. There is no magic to how they do it.

To add the second subtitle, rather than using the second subtitle track, they have the user manually switch the primary subtitle track to the secondary subtitle track and then add it to the card.

I had dreamed up a similar solution yesterday that I likely won't implement that involves switching the primary subtitle track to the secondary subtitle track for a split second when generating the card and then setting it back. The only issue is that creates graphical jank that you can't hide from the user since mpv flashes the secondary subtitle on screen for a split second. This is already a problem with the {screenshot} marker, but I consider the benefits to outweigh the negatives in that case since it won't interfere with anything else.

I'm not against contributing to mpv to solve this issue though. It's more a matter of are they willing to accept a pull request for something like this.

**Comment by TingTingin** [comment]
seems like you can access secondary sub-text now in mpv

https://github.com/mpv-player/mpv/pull/8822

**Comment by ripose-jp** [comment]
Looks good.

When it finally makes it into mpv releases, I'll be sure to add this feature.

**Comment by ripose-jp** [comment]
It's been added on the dev branch. The catch is that unless the mpv version supports the ```secondary-sub-text``` property, none of the features that rely on it will be visible.

I'll probably create two Windows downloads for the next release, one bundled with an unstable build of mpv (assuming I can get it to build on Windows) and one with version 0.33.1-r1.
![image](https://user-images.githubusercontent.com/72582120/122622746-91f96800-d04e-11eb-835b-67a8559ba7da.png)
