### ISSUE TITLE
Doesn't work with latest MacOs

### ISSUE THREAD

**Issue by chibigit** [ripose-jp/Memento#91]
Hi,

    I just downloaded Memento but it won't run. 
"You can’t open the application “Memento” because this application is not supported on this Mac."

I'm running Monterey 12.21

ta muchly

**Comment by ripose-jp** [comment]
Hard to say from that message alone because it works on my M1 Air.

Is is possible you accidentally download the Apple Silicon (arm) version instead of the Intel (x86_64) version?

If that doesn't work, what happens if you run the executable from Terminal?

1. Open **Terminal**
2. Assuming Memento is in the Applications folder, type: `/Applicaitons/Memento.app/Contents/MacOS/Memento`

**Comment by chibigit** [comment]
Oh quite right! Silly me! Yes, the x86 version works perfectly! Thank you!
Are there hot keys to jump to the previous subtitle? So you can jump back to read a subtitle you missed?

**Comment by ripose-jp** [comment]
Command+Left/Right
Here's a full list of keyboard binds and information on how to remap them: https://mpv.io/manual/stable/
Command takes the place of Ctrl on macOS.

**Comment by chibigit** [comment]
Oh of course! It's mpv! Doh!
