### ISSUE TITLE
Not parsing dictionary entry that Yomichan does

### ISSUE THREAD

**Issue by dkaknbk** [ripose-jp/Memento#92]
I just encountered a phrase (板につく) that Memento wasn't able to parse despite it being in the dictionary and working fine when trying in the browser with Yomichan. Pretty sure I encountered a similar case before but I forgot to take a screenshot that time.
![memento_2022-03-23@01_12_04](https://user-images.githubusercontent.com/78300742/159597726-2ca3c727-fdf2-4892-95c7-16267e3804d3.jpg)
![firefox_2022-03-23@01_12_13](https://user-images.githubusercontent.com/78300742/159597733-9058962f-ff70-4f18-8c4b-0122af4d0df6.jpg)
Thanks for the hard work as always by the way, really enjoy the new update! The option to replace newlines in Anki has already saved me a ton of time.

**Comment by ripose-jp** [comment]
MeCab appears to be parsing 板について as 板 and について
![image](https://user-images.githubusercontent.com/72582120/159602470-6513e2d4-a0ea-4d51-8777-ea755a551091.png)
You are correct that 板につく is in there, you can verify using manual search (Ctrl+R), but what ends up being searched is 板について. There may be a potential way to fix it, but the only reason it isn't implemented is because the time complexity seemed to be factorial if I remember correctly. I'll look into it to see if it's feasible or not.

**Comment by ripose-jp** [comment]
I was able to implement that algorithm and it seems to work well enough in the general case. It is almost certain to be slower, than the currently solution, but really what matters is if that's noticeable or not. I think there might be some optimization I can do if I can find a way to remove the recursive calls, but the current algorithm is good enough to enter testing.
![image](https://user-images.githubusercontent.com/72582120/159613950-960295f9-6148-484c-8ad9-1f10a94727f0.png)
