### ISSUE TITLE
Update dependencies for manual complication on the readme

### ISSUE THREAD

**Issue by eyalmazuz** [ripose-jp/Memento#94]
I tried compiling the new version of Memento today (I've used the AppImage until now)
and I got stuck with an error that basically was summed to this message:
```fatal error: mpv/client.h: No such file or directory ```
it was strange at first cause the dependencies mention MPV, and MPV comes preinstalled on Ubuntu by default.
I did a little searching and found out you need to install libmpv-dev (which also installs libmpv1) in order to get the header files required for compilation.
So I think it's better to mention specifically that those libs are needed as dependencies as well and not just MPV.

**Comment by ripose-jp** [comment]
The way dependencies are listed in the README is platform agnostic. They don't change whether you compile on Windows, macOS, or Linux.

As far as I know, Debian and its derivatives are the only distros that separate binaries and headers into different packages. That's a quirk of your specific distro that you're going to have to learn to work with. I also don't recommend compiling on Ubuntu because it's really a miserable experience due to outdated packages (#24). It may have changed since the last time I tried it, but it's a big part of why I supply AppImages in the first place.
